# Generated by Django 4.2.2 on 2023-06-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Surname')),
                ('job_title', models.CharField(choices=[('leader', 'Leader'), ('manager', 'Manager'), ('marketing_specialist', 'Marketing Specialist'), ('system_administrator', 'System Administrator'), ('employee', 'Employee')], default='employee', max_length=255)),
                ('employment_date', models.DateField(auto_now_add=True)),
                ('salary', models.FloatField()),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss_level', to='employee.employeedirectory')),
            ],
        ),
    ]
